# Generated by Django 5.2.6 on 2025-09-26 14:26

from django.db import migrations


def create_sample_properties(apps, schema_editor):
    Property = apps.get_model('property', 'Property')

    sample_properties = [
        {
            'title': 'Modern Downtown Apartment',
            'price': 250000,
            'city': 'New York',
            'image': 'properties/property_1_10.jpg'
        },
        {
            'title': 'Cozy Suburban House',
            'price': 180000,
            'city': 'Los Angeles',
            'image': 'properties/property_2_9.jpg'
        },
        {
            'title': 'Luxury Penthouse',
            'price': 500000,
            'city': 'Miami',
            'image': 'properties/property_3_8.jpg'
        },
        {
            'title': 'Family Home with Garden',
            'price': 320000,
            'city': 'Chicago',
            'image': 'properties/property_4_7.jpg'
        },
        {
            'title': 'Studio in City Center',
            'price': 150000,
            'city': 'San Francisco',
            'image': 'properties/property_5_6.jpg'
        },
        {
            'title': 'Beachfront Villa',
            'price': 750000,
            'city': 'Honolulu',
            'image': 'properties/property_6_5.jpg'
        },
        {
            'title': 'Mountain Cabin',
            'price': 280000,
            'city': 'Denver',
            'image': 'properties/property_7_4.jpg'
        },
        {
            'title': 'Historic Brownstone',
            'price': 420000,
            'city': 'Boston',
            'image': 'properties/property_8_3.jpg'
        },
        {
            'title': 'Modern Townhouse',
            'price': 350000,
            'city': 'Seattle',
            'image': 'properties/property_9_2.jpg'
        },
        {
            'title': 'Lakefront Property',
            'price': 600000,
            'city': 'Minneapolis',
            'image': 'properties/property_10_1.jpg'
        },
    ]

    for prop_data in sample_properties:
        Property.objects.create(**prop_data)


class Migration(migrations.Migration):

    dependencies = [
        ('property', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_properties),
    ]
